apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samplehtml-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - helloworld.lkoasisdev.com
      secretName: helloworld-lkoasisdev-com-tls
  rules:
    - host: helloworld.lkoasisdev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-app
                port:
                  number: 3000